jobName: pi

completions: 1
parallelism: 1
activeDeadlineSeconds: 120
ttlSecondsAfterFinished: 120

image:
  name: perl
  tag: 5.34.0

jobCommands:
  - perl
  - -Mbignum=bpi
  - -wle
  - print bpi(10000)
