apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}
  ports:
  - port: 80
    protocol: TCP
    name: http
